post:
  tags:
    - Reports
  summary: Deletes reports export configurations
  description: |
    Deletes unused reports export configurations. This endpoint allows bulk deletion of export configurations
    that are no longer needed. Spenders can only delete their own export configurations. If any of the 
    export configurations in the input do not exist or the user does not have permission to delete them, 
    a validation error is raised.
  operationId: reports_export_configurations_delete_bulk_post_spender
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          additionalProperties: false
          required:
            - data
          properties:
            data:
              type: array
              items: 
                $ref: '../../components/schemas/reports_export_configurations.yaml#/reports_export_configuration_in_only_id'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
    '401':
      description: Unauthorised request
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/401.yaml"
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                nullable: true
                example: You don't have permissions to access this resource
              data:
                type: object
                example: null
              error:
                type: string
                example: InvalidUsage
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "../../components/schemas/bulk_error.yaml"
              - type: object
                properties:
                  message:
                    type: string
                    nullable: true
                    example: |
                      Cannot delete export configuration(s) that do not exist or that you do not have permission to delete.
                  data:
                    type: object
                    example: null
                  error:
                    type: string
                    example: InvalidUsage

