openapi: 3.0.3
info:
  version: '1.0'
  title: Admin APIs
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: 'https://platform.fylehq.com/v1'
    description: Live Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            admin.*: Grant all ADMIN actions
tags:
  - name: Employees
    description: |
      These APIs gives you access to manage your organisation's Employees data.
  - name: Expenses
    description: |
      This API gives you access to your organisation's Expenses data.
  - name: Expense Fields
    description: |
      This API gives you access to your organisation's Expense Fields data.
  - name: Reports
    description: |
      This API gives you access to your organisation's Expense Reports data.
  - name: Advances
    description: |
      This API gives you access to Issued Advances data of your organisation.
  - name: Advance Requests
    description: |
      This API gives you access to your organisation's Advance Requests data.
  - name: Reimbursements
    description: >
      These APIs gives you access to manage your organisation's Reimbursements
      data.
  - name: Refunds
    description: |
      These APIs gives you access to manage your organisation's Refunds data.
  - name: Settlements
    description: >
      These APIs gives you access to manage your organisation's Settlements
      data.
  - name: Balance Transfers
    description: >
      These APIs gives you access to manage your organisation's Balance
      Transfers data.
  - name: Projects
    description: |
      These APIs gives you access to manage your organisation's Projects data.
  - name: Cost Centers
    description: >
      These APIs gives you access to manage your organisation's Cost Centers
      data.
  - name: Categories
    description: |
      These APIs gives you access to manage your organisation's Categories data.
paths:
  /admin/employees:
    $ref: paths/admin@employees.yaml
  /admin/expenses:
    $ref: paths/admin@expenses.yaml
  /admin/expense_fields:
    $ref: paths/admin@expense_fields.yaml
  /admin/reports:
    $ref: paths/admin@reports.yaml
  /admin/advance_requests:
    $ref: paths/admin@advance_requests.yaml
  /admin/advances:
    $ref: paths/admin@advances.yaml
  /admin/reimbursements:
    $ref: paths/admin@reimbursements.yaml
  /admin/refunds:
    $ref: paths/admin@refunds.yaml
  /admin/settlements:
    $ref: paths/admin@settlements.yaml
  /admin/balance_transfers:
    $ref: paths/admin@balance_transfers.yaml
  /admin/projects:
    $ref: paths/admin@projects.yaml
  /admin/categories:
    $ref: paths/admin@categories.yaml
  /admin/cost_centers:
    $ref: paths/admin@cost_centers.yaml
